name: Sync Calendly to Salesforce

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Sync Endpoint
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          echo "Triggering Calendly-Salesforce sync..."
          response=$(curl -s -w "\n%{http_code}" \
            -H "Authorization: Bearer $CRON_SECRET" \
            https://rendesco-bridge.vercel.app/api/cron/sync-calendly)
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          
          echo "Response: $body"
          echo "HTTP Status: $http_code"
          
          if [ "$http_code" != "200" ]; then
            echo "Error: Sync failed with status $http_code"
            exit 1
          fi
          
          echo "Sync completed successfully!"
